---
  - hosts: dev
    become: true
    tasks:
      - yum:
          name:
            - httpd
          state: present
      - service: name=httpd state=started enabled=yes
      - raw: "echo '{{ ansible_hostname }}' | sudo tee /var/www/html/index.html"
